#ifndef __USER_CONFIG_H__
#define __USER_CONFIG_H__

#define UART_BAUD_RATE 115200
#define UART_QUEUE_SIZE 1024

#define WIFI_DISC_SCAN_INTERVAL 6
#define WIFI_CONN_SCAN_INTERVAL 30

#define WEB_CONNECTIONS 2
#define WEB_REQ_BUFF_SIZE 1024
#define WEB_RESP_BUFF_SIZE 16384

#endif
